language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
before_install:
  - pip install --upgrade setuptools pip
  - pip install --upgrade pylint pytest pytest-pylint pytest-runner
install:
  - python setup.py develop
script:
  - python -m pytest  # Run the tests without IPython.
  - pip install ipython
  - python -m pytest  # Now run the tests with IPython.
  - if [[ $TRAVIS_PYTHON_VERSION != 3.6 ]]; then pylint fire --ignore=test_components_py3.py,parser_fuzz_test.py; fi
